spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  datasource:
    url: jdbc:mysql://mariadb:3306/poc_db?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
